// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	exportcsv "golang/module/exportcsv"

	mock "github.com/stretchr/testify/mock"
)

// ExportCSVController is an autogenerated mock type for the ExportCSVController type
type ExportCSVController struct {
	mock.Mock
}

type ExportCSVController_Expecter struct {
	mock *mock.Mock
}

func (_m *ExportCSVController) EXPECT() *ExportCSVController_Expecter {
	return &ExportCSVController_Expecter{mock: &_m.Mock}
}

// ExportCSV provides a mock function with given fields: req
func (_m *ExportCSVController) ExportCSV(req *exportcsv.ExportCSVRequest) ([][]string, error) {
	ret := _m.Called(req)

	var r0 [][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(*exportcsv.ExportCSVRequest) ([][]string, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*exportcsv.ExportCSVRequest) [][]string); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(*exportcsv.ExportCSVRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExportCSVController_ExportCSV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportCSV'
type ExportCSVController_ExportCSV_Call struct {
	*mock.Call
}

// ExportCSV is a helper method to define mock.On call
//   - req *exportcsv.ExportCSVRequest
func (_e *ExportCSVController_Expecter) ExportCSV(req interface{}) *ExportCSVController_ExportCSV_Call {
	return &ExportCSVController_ExportCSV_Call{Call: _e.mock.On("ExportCSV", req)}
}

func (_c *ExportCSVController_ExportCSV_Call) Run(run func(req *exportcsv.ExportCSVRequest)) *ExportCSVController_ExportCSV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*exportcsv.ExportCSVRequest))
	})
	return _c
}

func (_c *ExportCSVController_ExportCSV_Call) Return(_a0 [][]string, _a1 error) *ExportCSVController_ExportCSV_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExportCSVController_ExportCSV_Call) RunAndReturn(run func(*exportcsv.ExportCSVRequest) ([][]string, error)) *ExportCSVController_ExportCSV_Call {
	_c.Call.Return(run)
	return _c
}

// NewExportCSVController creates a new instance of ExportCSVController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExportCSVController(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExportCSVController {
	mock := &ExportCSVController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
