// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	transaction "golang/module/transaction"

	mock "github.com/stretchr/testify/mock"
)

// ControllerInterface is an autogenerated mock type for the ControllerInterface type
type ControllerInterface struct {
	mock.Mock
}

type ControllerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ControllerInterface) EXPECT() *ControllerInterface_Expecter {
	return &ControllerInterface_Expecter{mock: &_m.Mock}
}

// GetAllTransaction provides a mock function with given fields:
func (_m *ControllerInterface) GetAllTransaction() (*transaction.GetAllResponseDataTransaction, error) {
	ret := _m.Called()

	var r0 *transaction.GetAllResponseDataTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func() (*transaction.GetAllResponseDataTransaction, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *transaction.GetAllResponseDataTransaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.GetAllResponseDataTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_GetAllTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTransaction'
type ControllerInterface_GetAllTransaction_Call struct {
	*mock.Call
}

// GetAllTransaction is a helper method to define mock.On call
func (_e *ControllerInterface_Expecter) GetAllTransaction() *ControllerInterface_GetAllTransaction_Call {
	return &ControllerInterface_GetAllTransaction_Call{Call: _e.mock.On("GetAllTransaction")}
}

func (_c *ControllerInterface_GetAllTransaction_Call) Run(run func()) *ControllerInterface_GetAllTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ControllerInterface_GetAllTransaction_Call) Return(_a0 *transaction.GetAllResponseDataTransaction, _a1 error) *ControllerInterface_GetAllTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_GetAllTransaction_Call) RunAndReturn(run func() (*transaction.GetAllResponseDataTransaction, error)) *ControllerInterface_GetAllTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTransactionByDate provides a mock function with given fields: start, end
func (_m *ControllerInterface) GetAllTransactionByDate(start string, end string) (*transaction.GetAllResponseDataTransaction, error) {
	ret := _m.Called(start, end)

	var r0 *transaction.GetAllResponseDataTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*transaction.GetAllResponseDataTransaction, error)); ok {
		return rf(start, end)
	}
	if rf, ok := ret.Get(0).(func(string, string) *transaction.GetAllResponseDataTransaction); ok {
		r0 = rf(start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.GetAllResponseDataTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_GetAllTransactionByDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTransactionByDate'
type ControllerInterface_GetAllTransactionByDate_Call struct {
	*mock.Call
}

// GetAllTransactionByDate is a helper method to define mock.On call
//   - start string
//   - end string
func (_e *ControllerInterface_Expecter) GetAllTransactionByDate(start interface{}, end interface{}) *ControllerInterface_GetAllTransactionByDate_Call {
	return &ControllerInterface_GetAllTransactionByDate_Call{Call: _e.mock.On("GetAllTransactionByDate", start, end)}
}

func (_c *ControllerInterface_GetAllTransactionByDate_Call) Run(run func(start string, end string)) *ControllerInterface_GetAllTransactionByDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ControllerInterface_GetAllTransactionByDate_Call) Return(_a0 *transaction.GetAllResponseDataTransaction, _a1 error) *ControllerInterface_GetAllTransactionByDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_GetAllTransactionByDate_Call) RunAndReturn(run func(string, string) (*transaction.GetAllResponseDataTransaction, error)) *ControllerInterface_GetAllTransactionByDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTransactionByStatus provides a mock function with given fields: status
func (_m *ControllerInterface) GetAllTransactionByStatus(status string) (*transaction.GetAllResponseDataTransaction, error) {
	ret := _m.Called(status)

	var r0 *transaction.GetAllResponseDataTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*transaction.GetAllResponseDataTransaction, error)); ok {
		return rf(status)
	}
	if rf, ok := ret.Get(0).(func(string) *transaction.GetAllResponseDataTransaction); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.GetAllResponseDataTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_GetAllTransactionByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTransactionByStatus'
type ControllerInterface_GetAllTransactionByStatus_Call struct {
	*mock.Call
}

// GetAllTransactionByStatus is a helper method to define mock.On call
//   - status string
func (_e *ControllerInterface_Expecter) GetAllTransactionByStatus(status interface{}) *ControllerInterface_GetAllTransactionByStatus_Call {
	return &ControllerInterface_GetAllTransactionByStatus_Call{Call: _e.mock.On("GetAllTransactionByStatus", status)}
}

func (_c *ControllerInterface_GetAllTransactionByStatus_Call) Run(run func(status string)) *ControllerInterface_GetAllTransactionByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ControllerInterface_GetAllTransactionByStatus_Call) Return(_a0 *transaction.GetAllResponseDataTransaction, _a1 error) *ControllerInterface_GetAllTransactionByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_GetAllTransactionByStatus_Call) RunAndReturn(run func(string) (*transaction.GetAllResponseDataTransaction, error)) *ControllerInterface_GetAllTransactionByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTransactionByStatusDate provides a mock function with given fields: status, start, end
func (_m *ControllerInterface) GetAllTransactionByStatusDate(status string, start string, end string) (*transaction.GetAllResponseDataTransaction, error) {
	ret := _m.Called(status, start, end)

	var r0 *transaction.GetAllResponseDataTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*transaction.GetAllResponseDataTransaction, error)); ok {
		return rf(status, start, end)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *transaction.GetAllResponseDataTransaction); ok {
		r0 = rf(status, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.GetAllResponseDataTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(status, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_GetAllTransactionByStatusDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTransactionByStatusDate'
type ControllerInterface_GetAllTransactionByStatusDate_Call struct {
	*mock.Call
}

// GetAllTransactionByStatusDate is a helper method to define mock.On call
//   - status string
//   - start string
//   - end string
func (_e *ControllerInterface_Expecter) GetAllTransactionByStatusDate(status interface{}, start interface{}, end interface{}) *ControllerInterface_GetAllTransactionByStatusDate_Call {
	return &ControllerInterface_GetAllTransactionByStatusDate_Call{Call: _e.mock.On("GetAllTransactionByStatusDate", status, start, end)}
}

func (_c *ControllerInterface_GetAllTransactionByStatusDate_Call) Run(run func(status string, start string, end string)) *ControllerInterface_GetAllTransactionByStatusDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ControllerInterface_GetAllTransactionByStatusDate_Call) Return(_a0 *transaction.GetAllResponseDataTransaction, _a1 error) *ControllerInterface_GetAllTransactionByStatusDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_GetAllTransactionByStatusDate_Call) RunAndReturn(run func(string, string, string) (*transaction.GetAllResponseDataTransaction, error)) *ControllerInterface_GetAllTransactionByStatusDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionByDate provides a mock function with given fields: req, input
func (_m *ControllerInterface) GetTransactionByDate(req transaction.FilterByDate, input transaction.FilterLimit) (*transaction.GetAllResponseDataTransaction, error) {
	ret := _m.Called(req, input)

	var r0 *transaction.GetAllResponseDataTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(transaction.FilterByDate, transaction.FilterLimit) (*transaction.GetAllResponseDataTransaction, error)); ok {
		return rf(req, input)
	}
	if rf, ok := ret.Get(0).(func(transaction.FilterByDate, transaction.FilterLimit) *transaction.GetAllResponseDataTransaction); ok {
		r0 = rf(req, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.GetAllResponseDataTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(transaction.FilterByDate, transaction.FilterLimit) error); ok {
		r1 = rf(req, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_GetTransactionByDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionByDate'
type ControllerInterface_GetTransactionByDate_Call struct {
	*mock.Call
}

// GetTransactionByDate is a helper method to define mock.On call
//   - req transaction.FilterByDate
//   - input transaction.FilterLimit
func (_e *ControllerInterface_Expecter) GetTransactionByDate(req interface{}, input interface{}) *ControllerInterface_GetTransactionByDate_Call {
	return &ControllerInterface_GetTransactionByDate_Call{Call: _e.mock.On("GetTransactionByDate", req, input)}
}

func (_c *ControllerInterface_GetTransactionByDate_Call) Run(run func(req transaction.FilterByDate, input transaction.FilterLimit)) *ControllerInterface_GetTransactionByDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(transaction.FilterByDate), args[1].(transaction.FilterLimit))
	})
	return _c
}

func (_c *ControllerInterface_GetTransactionByDate_Call) Return(_a0 *transaction.GetAllResponseDataTransaction, _a1 error) *ControllerInterface_GetTransactionByDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_GetTransactionByDate_Call) RunAndReturn(run func(transaction.FilterByDate, transaction.FilterLimit) (*transaction.GetAllResponseDataTransaction, error)) *ControllerInterface_GetTransactionByDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionByStatusAndDate provides a mock function with given fields: req, input
func (_m *ControllerInterface) GetTransactionByStatusAndDate(req transaction.FilterByStatusDate, input transaction.FilterLimit) (*transaction.GetAllResponseDataTransaction, error) {
	ret := _m.Called(req, input)

	var r0 *transaction.GetAllResponseDataTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(transaction.FilterByStatusDate, transaction.FilterLimit) (*transaction.GetAllResponseDataTransaction, error)); ok {
		return rf(req, input)
	}
	if rf, ok := ret.Get(0).(func(transaction.FilterByStatusDate, transaction.FilterLimit) *transaction.GetAllResponseDataTransaction); ok {
		r0 = rf(req, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.GetAllResponseDataTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(transaction.FilterByStatusDate, transaction.FilterLimit) error); ok {
		r1 = rf(req, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_GetTransactionByStatusAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionByStatusAndDate'
type ControllerInterface_GetTransactionByStatusAndDate_Call struct {
	*mock.Call
}

// GetTransactionByStatusAndDate is a helper method to define mock.On call
//   - req transaction.FilterByStatusDate
//   - input transaction.FilterLimit
func (_e *ControllerInterface_Expecter) GetTransactionByStatusAndDate(req interface{}, input interface{}) *ControllerInterface_GetTransactionByStatusAndDate_Call {
	return &ControllerInterface_GetTransactionByStatusAndDate_Call{Call: _e.mock.On("GetTransactionByStatusAndDate", req, input)}
}

func (_c *ControllerInterface_GetTransactionByStatusAndDate_Call) Run(run func(req transaction.FilterByStatusDate, input transaction.FilterLimit)) *ControllerInterface_GetTransactionByStatusAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(transaction.FilterByStatusDate), args[1].(transaction.FilterLimit))
	})
	return _c
}

func (_c *ControllerInterface_GetTransactionByStatusAndDate_Call) Return(_a0 *transaction.GetAllResponseDataTransaction, _a1 error) *ControllerInterface_GetTransactionByStatusAndDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_GetTransactionByStatusAndDate_Call) RunAndReturn(run func(transaction.FilterByStatusDate, transaction.FilterLimit) (*transaction.GetAllResponseDataTransaction, error)) *ControllerInterface_GetTransactionByStatusAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// NewControllerInterface creates a new instance of ControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewControllerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ControllerInterface {
	mock := &ControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
