// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	account "golang/module/account"

	mock "github.com/stretchr/testify/mock"
)

// ControllerInterface is an autogenerated mock type for the ControllerInterface type
type ControllerInterface struct {
	mock.Mock
}

type ControllerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ControllerInterface) EXPECT() *ControllerInterface_Expecter {
	return &ControllerInterface_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: req
func (_m *ControllerInterface) CreateAccount(req *account.CreateRequest) (*account.CreateResponse, error) {
	ret := _m.Called(req)

	var r0 *account.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*account.CreateRequest) (*account.CreateResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*account.CreateRequest) *account.CreateResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*account.CreateRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type ControllerInterface_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - req *account.CreateRequest
func (_e *ControllerInterface_Expecter) CreateAccount(req interface{}) *ControllerInterface_CreateAccount_Call {
	return &ControllerInterface_CreateAccount_Call{Call: _e.mock.On("CreateAccount", req)}
}

func (_c *ControllerInterface_CreateAccount_Call) Run(run func(req *account.CreateRequest)) *ControllerInterface_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*account.CreateRequest))
	})
	return _c
}

func (_c *ControllerInterface_CreateAccount_Call) Return(_a0 *account.CreateResponse, _a1 error) *ControllerInterface_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_CreateAccount_Call) RunAndReturn(run func(*account.CreateRequest) (*account.CreateResponse, error)) *ControllerInterface_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDataUser provides a mock function with given fields: id
func (_m *ControllerInterface) DeleteDataUser(id string) (*account.CreateResponse, error) {
	ret := _m.Called(id)

	var r0 *account.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*account.CreateResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *account.CreateResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_DeleteDataUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDataUser'
type ControllerInterface_DeleteDataUser_Call struct {
	*mock.Call
}

// DeleteDataUser is a helper method to define mock.On call
//   - id string
func (_e *ControllerInterface_Expecter) DeleteDataUser(id interface{}) *ControllerInterface_DeleteDataUser_Call {
	return &ControllerInterface_DeleteDataUser_Call{Call: _e.mock.On("DeleteDataUser", id)}
}

func (_c *ControllerInterface_DeleteDataUser_Call) Run(run func(id string)) *ControllerInterface_DeleteDataUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ControllerInterface_DeleteDataUser_Call) Return(_a0 *account.CreateResponse, _a1 error) *ControllerInterface_DeleteDataUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_DeleteDataUser_Call) RunAndReturn(run func(string) (*account.CreateResponse, error)) *ControllerInterface_DeleteDataUser_Call {
	_c.Call.Return(run)
	return _c
}

// EditDataUser provides a mock function with given fields: id, req
func (_m *ControllerInterface) EditDataUser(id string, req *account.EditDataUserRequest) (*account.CreateResponse, error) {
	ret := _m.Called(id, req)

	var r0 *account.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *account.EditDataUserRequest) (*account.CreateResponse, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(string, *account.EditDataUserRequest) *account.CreateResponse); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *account.EditDataUserRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_EditDataUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditDataUser'
type ControllerInterface_EditDataUser_Call struct {
	*mock.Call
}

// EditDataUser is a helper method to define mock.On call
//   - id string
//   - req *account.EditDataUserRequest
func (_e *ControllerInterface_Expecter) EditDataUser(id interface{}, req interface{}) *ControllerInterface_EditDataUser_Call {
	return &ControllerInterface_EditDataUser_Call{Call: _e.mock.On("EditDataUser", id, req)}
}

func (_c *ControllerInterface_EditDataUser_Call) Run(run func(id string, req *account.EditDataUserRequest)) *ControllerInterface_EditDataUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*account.EditDataUserRequest))
	})
	return _c
}

func (_c *ControllerInterface_EditDataUser_Call) Return(_a0 *account.CreateResponse, _a1 error) *ControllerInterface_EditDataUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_EditDataUser_Call) RunAndReturn(run func(string, *account.EditDataUserRequest) (*account.CreateResponse, error)) *ControllerInterface_EditDataUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetDataUser provides a mock function with given fields:
func (_m *ControllerInterface) GetDataUser() (*account.ReadResponse, error) {
	ret := _m.Called()

	var r0 *account.ReadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*account.ReadResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *account.ReadResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ReadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_GetDataUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataUser'
type ControllerInterface_GetDataUser_Call struct {
	*mock.Call
}

// GetDataUser is a helper method to define mock.On call
func (_e *ControllerInterface_Expecter) GetDataUser() *ControllerInterface_GetDataUser_Call {
	return &ControllerInterface_GetDataUser_Call{Call: _e.mock.On("GetDataUser")}
}

func (_c *ControllerInterface_GetDataUser_Call) Run(run func()) *ControllerInterface_GetDataUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ControllerInterface_GetDataUser_Call) Return(_a0 *account.ReadResponse, _a1 error) *ControllerInterface_GetDataUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_GetDataUser_Call) RunAndReturn(run func() (*account.ReadResponse, error)) *ControllerInterface_GetDataUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetDataUserById provides a mock function with given fields: id
func (_m *ControllerInterface) GetDataUserById(id string) (*account.ReadResponse, error) {
	ret := _m.Called(id)

	var r0 *account.ReadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*account.ReadResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *account.ReadResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ReadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_GetDataUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataUserById'
type ControllerInterface_GetDataUserById_Call struct {
	*mock.Call
}

// GetDataUserById is a helper method to define mock.On call
//   - id string
func (_e *ControllerInterface_Expecter) GetDataUserById(id interface{}) *ControllerInterface_GetDataUserById_Call {
	return &ControllerInterface_GetDataUserById_Call{Call: _e.mock.On("GetDataUserById", id)}
}

func (_c *ControllerInterface_GetDataUserById_Call) Run(run func(id string)) *ControllerInterface_GetDataUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ControllerInterface_GetDataUserById_Call) Return(_a0 *account.ReadResponse, _a1 error) *ControllerInterface_GetDataUserById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_GetDataUserById_Call) RunAndReturn(run func(string) (*account.ReadResponse, error)) *ControllerInterface_GetDataUserById_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: req
func (_m *ControllerInterface) Login(req *account.LoginResponseRequest) (string, *account.LoginResponse, error) {
	ret := _m.Called(req)

	var r0 string
	var r1 *account.LoginResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(*account.LoginResponseRequest) (string, *account.LoginResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*account.LoginResponseRequest) string); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*account.LoginResponseRequest) *account.LoginResponse); ok {
		r1 = rf(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*account.LoginResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(*account.LoginResponseRequest) error); ok {
		r2 = rf(req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ControllerInterface_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type ControllerInterface_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - req *account.LoginResponseRequest
func (_e *ControllerInterface_Expecter) Login(req interface{}) *ControllerInterface_Login_Call {
	return &ControllerInterface_Login_Call{Call: _e.mock.On("Login", req)}
}

func (_c *ControllerInterface_Login_Call) Run(run func(req *account.LoginResponseRequest)) *ControllerInterface_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*account.LoginResponseRequest))
	})
	return _c
}

func (_c *ControllerInterface_Login_Call) Return(_a0 string, _a1 *account.LoginResponse, _a2 error) *ControllerInterface_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ControllerInterface_Login_Call) RunAndReturn(run func(*account.LoginResponseRequest) (string, *account.LoginResponse, error)) *ControllerInterface_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewControllerInterface creates a new instance of ControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewControllerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ControllerInterface {
	mock := &ControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
