// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	account "golang/module/account"

	mock "github.com/stretchr/testify/mock"
)

// ControllerInterface is an autogenerated mock type for the ControllerInterface type
type ControllerInterface struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: req
func (_m *ControllerInterface) CreateAccount(req *account.CreateRequest) (*account.CreateResponse, error) {
	ret := _m.Called(req)

	var r0 *account.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*account.CreateRequest) (*account.CreateResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*account.CreateRequest) *account.CreateResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*account.CreateRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDataUser provides a mock function with given fields: id
func (_m *ControllerInterface) DeleteDataUser(id string) (*account.CreateResponse, error) {
	ret := _m.Called(id)

	var r0 *account.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*account.CreateResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *account.CreateResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EditDataUser provides a mock function with given fields: id, req
func (_m *ControllerInterface) EditDataUser(id string, req *account.EditDataUserRequest) (*account.CreateResponse, error) {
	ret := _m.Called(id, req)

	var r0 *account.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *account.EditDataUserRequest) (*account.CreateResponse, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(string, *account.EditDataUserRequest) *account.CreateResponse); ok {
		r0 = rf(id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *account.EditDataUserRequest) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDataUser provides a mock function with given fields:
func (_m *ControllerInterface) GetDataUser() (*account.ReadResponse, error) {
	ret := _m.Called()

	var r0 *account.ReadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*account.ReadResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *account.ReadResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ReadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDataUserById provides a mock function with given fields: id
func (_m *ControllerInterface) GetDataUserById(id string) (*account.ReadResponse, error) {
	ret := _m.Called(id)

	var r0 *account.ReadResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*account.ReadResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *account.ReadResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ReadResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: req
func (_m *ControllerInterface) Login(req *account.LoginResponseRequest) (string, *account.LoginResponse, error) {
	ret := _m.Called(req)

	var r0 string
	var r1 *account.LoginResponse
	var r2 error
	if rf, ok := ret.Get(0).(func(*account.LoginResponseRequest) (string, *account.LoginResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*account.LoginResponseRequest) string); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*account.LoginResponseRequest) *account.LoginResponse); ok {
		r1 = rf(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*account.LoginResponse)
		}
	}

	if rf, ok := ret.Get(2).(func(*account.LoginResponseRequest) error); ok {
		r2 = rf(req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewControllerInterface creates a new instance of ControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewControllerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ControllerInterface {
	mock := &ControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
