// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	account "golang/module/account"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryInterface is an autogenerated mock type for the RepositoryInterface type
type RepositoryInterface struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: req
func (_m *RepositoryInterface) CreateAccount(req *account.Account) (account.Account, error) {
	ret := _m.Called(req)

	var r0 account.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(*account.Account) (account.Account, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*account.Account) account.Account); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(account.Account)
	}

	if rf, ok := ret.Get(1).(func(*account.Account) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDataUser provides a mock function with given fields: id
func (_m *RepositoryInterface) DeleteDataUser(id string) (account.Account, error) {
	ret := _m.Called(id)

	var r0 account.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (account.Account, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) account.Account); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(account.Account)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EditDataUser provides a mock function with given fields: id, req
func (_m *RepositoryInterface) EditDataUser(id string, req *account.Account) (account.Account, error) {
	ret := _m.Called(id, req)

	var r0 account.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *account.Account) (account.Account, error)); ok {
		return rf(id, req)
	}
	if rf, ok := ret.Get(0).(func(string, *account.Account) account.Account); ok {
		r0 = rf(id, req)
	} else {
		r0 = ret.Get(0).(account.Account)
	}

	if rf, ok := ret.Get(1).(func(string, *account.Account) error); ok {
		r1 = rf(id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDataUser provides a mock function with given fields:
func (_m *RepositoryInterface) GetDataUser() ([]account.Account, error) {
	ret := _m.Called()

	var r0 []account.Account
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]account.Account, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []account.Account); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]account.Account)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDataUserById provides a mock function with given fields: id
func (_m *RepositoryInterface) GetDataUserById(id string) (account.Account, error) {
	ret := _m.Called(id)

	var r0 account.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (account.Account, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) account.Account); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(account.Account)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: req
func (_m *RepositoryInterface) Login(req *account.Account) (string, account.Account, error) {
	ret := _m.Called(req)

	var r0 string
	var r1 account.Account
	var r2 error
	if rf, ok := ret.Get(0).(func(*account.Account) (string, account.Account, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*account.Account) string); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*account.Account) account.Account); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Get(1).(account.Account)
	}

	if rf, ok := ret.Get(2).(func(*account.Account) error); ok {
		r2 = rf(req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewRepositoryInterface creates a new instance of RepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryInterface {
	mock := &RepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
